DROP DATABASE IF EXISTS gym_db;
CREATE DATABASE gym_db;

USE gym_db;

CREATE TABLE users (
    id INT AUTO_INCREMENT NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    instructor BOOLEAN DEFAULT false,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE classes (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    startTime DATETIME NOT NULL,
    endTime DATETIME NOT NULL,
    price INT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    instructorId INT,
    PRIMARY KEY(id),
    FOREIGN KEY(instructorId) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE userClasses (
    id INT AUTO_INCREMENT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    userId INT NOT NULL,
    classId INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(classId) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE classReviews (
    id INT AUTO_INCREMENT NOT NULL,
    review TEXT NOT NULL,
    rating INT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    authorId INT NOT NULL, 
    classId INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(authorId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(classId) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE instructorReviews (
    id INT AUTO_INCREMENT NOT NULL,
    review TEXT NOT NULL,
    rating INT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    authorId INT NOT NULL, 
    instructorId INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(authorId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(instructorId) REFERENCES users(id) ON DELETE CASCADE
);

SELECT * FROM users;
SELECT * FROM classes;
SELECT * FROM userClasses;
SELECT * FROM classReviews;
SELECT * FROM instructorReviews;
